### ISSUE TITLE
Json type

### ISSUE THREAD

**Issue by neurosnap** [nettofarah/postgres-schema-ts#2]
Greetings!

Nice job on this project, it works for my purposes.  I was wondering how receptive you would be to changing the `jsonb` type to something that more closely resembles the values that are possible for `json` and `jsonb`?

For example, `zapatos` uses this type for its value: https://github.com/jawj/zapatos/blob/master/src/db/core.ts#L44

I'd be happy to help submit a PR for this if you're interested in adopting this change.

**Comment by nettofarah** [comment]
That sounds awesome, @neurosnap. Let's do it.

**Comment by stephenmathieson** [comment]
Hey Netto 👋 

Hope you're well! This is a great little project. It's saved me a bunch of time!

I'd also like to see better handling of `jsonb` here. I've got this table:

```
# \d distinct_ids
             Table "public.distinct_ids"
   Column    | Type  | Collation | Nullable | Default
-------------+-------+-----------+----------+---------
 keycloak_id | uuid  |           | not null |
 distinct_id | uuid  |           | not null |
 data        | jsonb |           |          |
Indexes:
    "distinct_ids_pkey" PRIMARY KEY, btree (keycloak_id)
```

Which is currently generating the following type:

```ts
export interface distinct_ids {
  keycloak_id: string
  distinct_id: string
  data: Object | null
}
```

Using `Object` technically works, but doing something like `data: any` may be slightly better.

What do you think?

**Comment by stephenmathieson** [comment]
Better yet, maybe `Record<string, unknown>`?

**Comment by nettofarah** [comment]
We could use a JSON type too. 
How about something like this? https://github.com/nettofarah/mysql-schema-ts/blob/711b6419e227aea7e2f22ce8777768e823869f91/src/index.ts#L13-L17

**Comment by stephenmathieson** [comment]
Yes, that would be great! 🎉 

I'll try to find some time to get a patch together in the next few days (unless you get to it first).
